//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNHeader()
        {
            this.CNCancel = new HashSet<CNCancel>();
            this.CNDetails = new HashSet<CNDetails>();
        }
    
        public string No { get; set; }
        public bool Enable { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKPosHeader { get; set; }
        public decimal TotalBalance { get; set; }
        public decimal TotalVat { get; set; }
        public decimal TotaNoVat { get; set; }
        public decimal Total { get; set; }
        public decimal TotalBeforeVat { get; set; }
        public decimal QtyList { get; set; }
        public decimal Qty { get; set; }
        public int FKCNType { get; set; }
        public int SequenceNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNCancel> CNCancel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNDetails> CNDetails { get; set; }
        public virtual CNType CNType { get; set; }
        public virtual PosHeader PosHeader { get; set; }
    }
}
