//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostProductChangeLog
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public bool Enable { get; set; }
        public int FKProduct { get; set; }
        public decimal CurrentCostOnly { get; set; }
        public decimal CurrentCostAndVat { get; set; }
        public decimal OldCostOnly { get; set; }
        public decimal OldCostAndVat { get; set; }
        public bool IsHigher { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
