//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISS2Front
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ISS2Front()
        {
            this.ISS2FrontDetails = new HashSet<ISS2FrontDetails>();
        }
    
        public string Code { get; set; }
        public bool Enable { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> FKEmployee { get; set; }
        public decimal TotalQty { get; set; }
        public decimal TotalQtyUnit { get; set; }
        public decimal TotalUnVat { get; set; }
        public decimal TotalBeforeVat { get; set; }
        public decimal TotalVat { get; set; }
        public decimal TotalBalance { get; set; }
        public int FKISS2FrontStatus { get; set; }
        public Nullable<System.DateTime> Takedate { get; set; }
        public string TakeBy { get; set; }
        public string Remark { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ISS2FrontStatus ISS2FrontStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISS2FrontDetails> ISS2FrontDetails { get; set; }
    }
}
