//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingSchedule
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public bool Enable { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKMember { get; set; }
        public int FKMeeting { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Member Member { get; set; }
    }
}
