//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberChangeMoney2560
    {
        public int Id { get; set; }
        public bool Enable { get; set; }
        public string หมายเลข { get; set; }
        public string ช__อ_สก_ล { get; set; }
        public string เพศ { get; set; }
        public string ยกมา { get; set; }
        public double ค_างจ_าย { get; set; }
        public double ห__น { get; set; }
        public double จำนวนเง_น { get; set; }
        public string ไม_เต_มป_ { get; set; }
        public string ไม_เต_มป_1 { get; set; }
        public string จำนวนเง_น1 { get; set; }
        public double ป_60 { get; set; }
        public double รวม { get; set; }
        public double ค_างจ_าย1 { get; set; }
        public double ยอดซ__อห_ก_7_ { get; set; }
        public double ป_601 { get; set; }
        public double เฉล__ยค_นป_60 { get; set; }
        public double ค_ปอง { get; set; }
        public double เฉล__ยค_นค_ปองป_60 { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string PrintBy { get; set; }
        public int PrintNumber { get; set; }
        public string ReceiptNo { get; set; }
        public decimal GetAmount { get; set; }
        public int GetType { get; set; }
    }
}
