//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickingLocation
    {
        public int Id { get; set; }
        public int FKPickingDetail { get; set; }
        public int FKCurrentStock { get; set; }
        public decimal Qty { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string ConfirmBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public bool Enable { get; set; }
    
        public virtual CurrentStocks CurrentStocks { get; set; }
        public virtual PickingDetails PickingDetails { get; set; }
    }
}
