//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickingDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PickingDetails()
        {
            this.PickingLocation = new HashSet<PickingLocation>();
        }
    
        public int Id { get; set; }
        public int FKPicking { get; set; }
        public int FKProductDetail { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime ProductDate { get; set; }
        public int FKItemStatus { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string ConfirmBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public bool Enable { get; set; }
    
        public virtual ItemStatus ItemStatus { get; set; }
        public virtual Pickings Pickings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickingLocation> PickingLocation { get; set; }
    }
}
