//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODetail
    {
        public int Id { get; set; }
        public int FKPOHeader { get; set; }
        public int FKProductDetail { get; set; }
        public decimal Qty { get; set; }
        public decimal GiftQty { get; set; }
        public decimal CostOnly { get; set; }
        public decimal CostAndVat { get; set; }
        public string DiscountInput { get; set; }
        public decimal DiscountBath { get; set; }
        public decimal TotalCost { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public bool Enable { get; set; }
        public decimal RcvQty { get; set; }
        public decimal RcvGiftQty { get; set; }
        public Nullable<System.DateTime> InterfaceDate { get; set; }
        public int Sequence { get; set; }
    
        public virtual POHeader POHeader { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
