//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class POHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POHeader()
        {
            this.PODetail = new HashSet<PODetail>();
            this.PORcv = new HashSet<PORcv>();
            this.PORcvCash = new HashSet<PORcvCash>();
        }
    
        public int Id { get; set; }
        public int FKBranch { get; set; }
        public int FKVender { get; set; }
        public string PONo { get; set; }
        public System.DateTime PODate { get; set; }
        public int FKBudgetYear { get; set; }
        public string ReferenceNo { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime POExpire { get; set; }
        public int FKPaymentType { get; set; }
        public string DiscountInput { get; set; }
        public string DiscountBath { get; set; }
        public string DiscountPercent { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> NotApproveDate { get; set; }
        public string NotApproveBy { get; set; }
        public string NotApproveRemark { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveBy { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalHasVat { get; set; }
        public decimal TotalUnVat { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalPriceDiscount { get; set; }
        public decimal TotalVat { get; set; }
        public decimal TotalBalance { get; set; }
        public decimal TotalQty { get; set; }
        public decimal TotalGift { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public bool Enable { get; set; }
        public int FKPOStatus { get; set; }
        public Nullable<System.DateTime> UnApproveDate { get; set; }
        public string UpApproveBy { get; set; }
        public string UpApproveRemark { get; set; }
        public int SequenceEdit { get; set; }
        public bool IsGet { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual BudgetYear BudgetYear { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODetail> PODetail { get; set; }
        public virtual POStatus POStatus { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORcv> PORcv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORcvCash> PORcvCash { get; set; }
    }
}
