//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORcvCashDetails
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKPORcvCash { get; set; }
        public int FKRcvInvoice { get; set; }
        public int FKProductDtl { get; set; }
        public int SequenceNumber { get; set; }
        public decimal RcvQuantity { get; set; }
        public decimal CurrentCost { get; set; }
        public decimal NewCost { get; set; }
        public string DiscountKey { get; set; }
        public decimal DiscountBath { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal GiftQty { get; set; }
    
        public virtual PORcvCash PORcvCash { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
