//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORcvCash
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PORcvCash()
        {
            this.PORcvCashDetails = new HashSet<PORcvCashDetails>();
        }
    
        public int Id { get; set; }
        public int FKPOHeader { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public string DiscountKey { get; set; }
        public decimal DiscountBath { get; set; }
        public decimal TotalBUnVat { get; set; }
        public decimal TotalBHasVat { get; set; }
        public decimal TotalVat { get; set; }
        public decimal TotalGift { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string InvoiceNo { get; set; }
        public int FKTransport { get; set; }
        public string TransportRemark { get; set; }
        public string DriverName { get; set; }
    
        public virtual POHeader POHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORcvCashDetails> PORcvCashDetails { get; set; }
    }
}
