//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PosDetails()
        {
            this.CNDetails = new HashSet<CNDetails>();
        }
    
        public int Id { get; set; }
        public bool Enable { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKPosHeader { get; set; }
        public int FKProductDetails { get; set; }
        public decimal Qty { get; set; }
        public decimal Cost { get; set; }
        public decimal PricePerUnit { get; set; }
        public decimal DiscountCoupon { get; set; }
        public decimal DiscountShop { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal TotalBeforeVat { get; set; }
        public decimal TotalVat { get; set; }
        public bool IsPromotion { get; set; }
        public decimal Packsize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNDetails> CNDetails { get; set; }
        public virtual PosHeader PosHeader { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
