//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessedGoods
    {
        public int Id { get; set; }
        public int FKProductDtl { get; set; }
        public string Barcode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public decimal CostOnly { get; set; }
        public decimal CostAndVat { get; set; }
        public decimal CostVat { get; set; }
        public decimal PackSize { get; set; }
        public decimal SellPrice { get; set; }
        public decimal Qty { get; set; }
        public string Description { get; set; }
        public bool Enable { get; set; }
    
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
