//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetails()
        {
            this.SaleOrderWarehouseDtl = new HashSet<SaleOrderWarehouseDtl>();
            this.AdjustStoreFrontDetail = new HashSet<AdjustStoreFrontDetail>();
            this.CheckStockDetails = new HashSet<CheckStockDetails>();
            this.CostDtlChangeLog = new HashSet<CostDtlChangeLog>();
            this.GetGoodsStoreFrontDetails = new HashSet<GetGoodsStoreFrontDetails>();
            this.ISS2FrontDetails = new HashSet<ISS2FrontDetails>();
            this.PODetail = new HashSet<PODetail>();
            this.PORcvCashDetails = new HashSet<PORcvCashDetails>();
            this.PORcvDetails = new HashSet<PORcvDetails>();
            this.PosDetails = new HashSet<PosDetails>();
            this.PosStockDetails = new HashSet<PosStockDetails>();
            this.ProcessedGoods = new HashSet<ProcessedGoods>();
            this.SellingPrice = new HashSet<SellingPrice>();
            this.SellingPriceDetails = new HashSet<SellingPriceDetails>();
            this.SellPriceChangeLog = new HashSet<SellPriceChangeLog>();
            this.StoreFrontStockDetails = new HashSet<StoreFrontStockDetails>();
            this.StoreFrontTransferOutDtl = new HashSet<StoreFrontTransferOutDtl>();
            this.StoreFrontTransferWasteDtl = new HashSet<StoreFrontTransferWasteDtl>();
            this.StoreFrontValueSet = new HashSet<StoreFrontValueSet>();
            this.CNWarehouseDetails = new HashSet<CNWarehouseDetails>();
            this.CurrentStocks = new HashSet<CurrentStocks>();
            this.WarehouseToWasteDetails = new HashSet<WarehouseToWasteDetails>();
            this.WasteWarehouseDetails = new HashSet<WasteWarehouseDetails>();
            this.WmsStockDetail = new HashSet<WmsStockDetail>();
            this.WmsTransferOutDetails = new HashSet<WmsTransferOutDetails>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal PackSize { get; set; }
        public decimal CostOnly { get; set; }
        public decimal CostAndVat { get; set; }
        public decimal CostVat { get; set; }
        public bool IsPrintLabel { get; set; }
        public decimal SellPrice { get; set; }
        public int FKProduct { get; set; }
        public int FKUnit { get; set; }
        public Nullable<decimal> SpecialQtyPiece { get; set; }
        public bool SetPallet { get; set; }
        public int PalletRow { get; set; }
        public int PalletLevel { get; set; }
        public int PalletTotal { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public bool Enable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderWarehouseDtl> SaleOrderWarehouseDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustStoreFrontDetail> AdjustStoreFrontDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckStockDetails> CheckStockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostDtlChangeLog> CostDtlChangeLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GetGoodsStoreFrontDetails> GetGoodsStoreFrontDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISS2FrontDetails> ISS2FrontDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODetail> PODetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORcvCashDetails> PORcvCashDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORcvDetails> PORcvDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosDetails> PosDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosStockDetails> PosStockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcessedGoods> ProcessedGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellingPrice> SellingPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellingPriceDetails> SellingPriceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellPriceChangeLog> SellPriceChangeLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreFrontStockDetails> StoreFrontStockDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreFrontTransferOutDtl> StoreFrontTransferOutDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreFrontTransferWasteDtl> StoreFrontTransferWasteDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreFrontValueSet> StoreFrontValueSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNWarehouseDetails> CNWarehouseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentStocks> CurrentStocks { get; set; }
        public virtual Products Products { get; set; }
        public virtual ProductUnit ProductUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarehouseToWasteDetails> WarehouseToWasteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WasteWarehouseDetails> WasteWarehouseDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WmsStockDetail> WmsStockDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WmsTransferOutDetails> WmsTransferOutDetails { get; set; }
    }
}
