//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcvDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RcvDetails()
        {
            this.RcvLocation = new HashSet<RcvLocation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FKRcvHeader { get; set; }
        public Nullable<int> FKPo { get; set; }
        public int FKProductDetail { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime ProductDate { get; set; }
        public Nullable<int> FKLocation { get; set; }
        public Nullable<int> PalletNo { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string ConfirmBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public bool Enable { get; set; }
    
        public virtual Locations Locations { get; set; }
        public virtual RcvHeader RcvHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcvLocation> RcvLocation { get; set; }
    }
}
