//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderWarehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleOrderWarehouse()
        {
            this.SaleOrderWarehouseDtl = new HashSet<SaleOrderWarehouseDtl>();
        }
    
        public bool Enable { get; set; }
        public int Id { get; set; }
        public string Code { get; set; }
        public string CodeRefer { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKBranch { get; set; }
        public int FKDebtor { get; set; }
        public int FKDelivery { get; set; }
        public int FKPayment { get; set; }
        public decimal TotalVat { get; set; }
        public decimal TotaNoVat { get; set; }
        public decimal TotalBeforeVat { get; set; }
        public decimal Total { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalDiscountInList { get; set; }
        public decimal PercentDiscount { get; set; }
        public decimal BathDiscount { get; set; }
        public string DiscountRemark { get; set; }
        public Nullable<System.DateTime> TakeDate { get; set; }
        public string TakeBy { get; set; }
        public string Remark { get; set; }
        public int FKSaleOrderWarehouseStatus { get; set; }
        public string ProjectName { get; set; }
        public int FKMember { get; set; }
        public decimal TotalBalance { get; set; }
        public string ConfirmOrderBy { get; set; }
        public Nullable<System.DateTime> ConfirmOrderDate { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceNoWH { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Debtor Debtor { get; set; }
        public virtual Member Member { get; set; }
        public virtual DeliveryType DeliveryType { get; set; }
        public virtual PaymentType PaymentType { get; set; }
        public virtual SaleOrderWarehouseStatus SaleOrderWarehouseStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderWarehouseDtl> SaleOrderWarehouseDtl { get; set; }
    }
}
