//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderWarehouseDtl
    {
        public bool Enable { get; set; }
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKProductDtl { get; set; }
        public int FKSaleOrderWarehouse { get; set; }
        public decimal Qty { get; set; }
        public decimal QtyAllow { get; set; }
        public decimal PricePerUnit { get; set; }
        public decimal PercentDiscount { get; set; }
        public decimal BathDiscount { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal QtyOriginal { get; set; }
    
        public virtual SaleOrderWarehouse SaleOrderWarehouse { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
