//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellingPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SellingPrice()
        {
            this.SellingPriceDetails = new HashSet<SellingPriceDetails>();
        }
    
        public int Id { get; set; }
        public bool Enable { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKPriceSchedule { get; set; }
        public int FKProduct { get; set; }
        public decimal GetCurrentPrice { get; set; }
        public decimal SpecialPrice { get; set; }
        public decimal FullyQty { get; set; }
    
        public virtual PriceSchedule PriceSchedule { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellingPriceDetails> SellingPriceDetails { get; set; }
    }
}
