//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellingPriceDetails
    {
        public int Id { get; set; }
        public bool Enable { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKSellingPrice { get; set; }
        public int FKProduct { get; set; }
        public decimal GiftQty { get; set; }
        public decimal GetCurrentPrice { get; set; }
        public decimal SpecialPrice { get; set; }
    
        public virtual SellingPrice SellingPrice { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
