//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreFrontValueSet
    {
        public int Id { get; set; }
        public bool Enable { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKProductDetails { get; set; }
        public int Number { get; set; }
        public string FKDocNo { get; set; }
        public decimal QtyUnit1 { get; set; }
        public decimal QtyUnit2 { get; set; }
        public decimal SellPricePerUnit { get; set; }
        public decimal CostOnlyPerUnit { get; set; }
        public decimal Total { get; set; }
        public decimal Packsize { get; set; }
        public Nullable<System.DateTime> UpStockDate { get; set; }
        public int FKWarehouse { get; set; }
    
        public virtual StoreFrontValueDoc StoreFrontValueDoc { get; set; }
        public virtual ProductDetails ProductDetails { get; set; }
    }
}
