//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreFrontTransferWaste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreFrontTransferWaste()
        {
            this.StoreFrontTransferWasteDtl = new HashSet<StoreFrontTransferWasteDtl>();
        }
    
        public string Code { get; set; }
        public bool Enable { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public decimal TotalQty { get; set; }
        public decimal TotalQtyUnit { get; set; }
        public int FKWarehouse { get; set; }
        public int FKWasteReason { get; set; }
    
        public virtual Warehouse Warehouse { get; set; }
        public virtual WasteReason WasteReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreFrontTransferWasteDtl> StoreFrontTransferWasteDtl { get; set; }
    }
}
