//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreFrontValueDoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreFrontValueDoc()
        {
            this.StoreFrontValueSet = new HashSet<StoreFrontValueSet>();
        }
    
        public string DocNo { get; set; }
        public System.DateTime DocDate { get; set; }
        public string UpdateBy { get; set; }
        public bool Enable { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool Used { get; set; }
        public decimal TotalCostOnly { get; set; }
        public int SaveNumber { get; set; }
        public decimal TotalQtyUnit { get; set; }
        public Nullable<System.DateTime> ConfirmCheck1Date { get; set; }
        public string ConfirmCheck1By { get; set; }
        public Nullable<System.DateTime> ConfirmCheck2Date { get; set; }
        public string ConfirmCheck2By { get; set; }
        public int PrintNumber { get; set; }
        public Nullable<System.DateTime> UpStockDate { get; set; }
        public int FKWarehouse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreFrontValueSet> StoreFrontValueSet { get; set; }
    }
}
