//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseToWasteDetails
    {
        public int Id { get; set; }
        public bool Enable { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKProductDetails { get; set; }
        public decimal QtyUnit { get; set; }
        public int FKWarehouseToWaste { get; set; }
        public decimal Packsize { get; set; }
        public decimal PricePerUnit { get; set; }
        public string Location { get; set; }
    
        public virtual ProductDetails ProductDetails { get; set; }
        public virtual WarehouseToWaste WarehouseToWaste { get; set; }
    }
}
