//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStart
{
    using System;
    using System.Collections.Generic;
    
    public partial class WasteWarehouseDetails
    {
        public int Id { get; set; }
        public string DocReference { get; set; }
        public string Description { get; set; }
        public bool Enable { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdateBy { get; set; }
        public int FKWasteWarehouse { get; set; }
        public int FKProductDetails { get; set; }
        public decimal QtyUnit { get; set; }
        public decimal Packsize { get; set; }
        public decimal QtyPiece { get; set; }
        public bool IsInOrOut { get; set; }
        public decimal LastResultUnit { get; set; }
        public decimal LastResultPiece { get; set; }
        public Nullable<System.DateTime> ConfirmCNDate { get; set; }
        public string ConfirmCNBy { get; set; }
        public decimal CostOnly { get; set; }
        public decimal SellPrice { get; set; }
    
        public virtual ProductDetails ProductDetails { get; set; }
        public virtual WasteWarehouse WasteWarehouse { get; set; }
    }
}
